# Description:
#   Pdf Parser protos.

package(default_visibility = ["//:internal_users"])

load("//cpu_instructions:proto_library.bzl", "cpu_instructions_proto_library")

licenses(["notice"])  # Apache 2.0

cpu_instructions_proto_library(
    name = "pdf_document_proto",
    srcs = ["pdf_document.proto"],
    cc_api_version = 2,
)
