# Description:
#   Proto utilities.

package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

cc_library(
    name = "repeated_field_util",
    hdrs = ["repeated_field_util.h"],
)
