# Definition:
#   Base functions.

package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

cc_library(
    name = "base",
    hdrs = [
        "macros.h",
        "stringprintf.h",
    ],
    deps = [
        "@protobuf_git//:protobuf_lite",
    ],
)
