# Definition:
#   Base functions.

package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

cc_library(
    name = "base",
    hdrs = [
        "casts.h",
    ],
    deps = [
        "@com_google_protobuf//:protobuf_lite",
    ],
)
