document_id {
  title: "Intel\302\256 64 and IA-32 Architectures Software Developers Manual, Combined Volumes: 1, 2A, 2B, 2C, 2D, 3A, 3B, 3C and 3D"
  creation_date: "D:20161228212902Z"
  modification_date: "D:20161228215347-08\'00\'"
}
pages {
  page_number: 603
  patches {
    row: 13
    expected: "FV-RVM"
    replacement: "FV"
  }
}
pages {
  page_number: 606
  patches {
    row: 13
    expected: "FV-RVM"
    replacement: "FV"
  }
}
pages {
  page_number: 609
  patches {
    row: 10
    expected: "T1S-RVM"
    replacement: "T1S"
  }
}
pages {
  page_number: 692
  patches {
    row: 3
    col: 2
    expected: "M"
    replacement: "D"
  }
  patches {
    row: 4
    col: 2
    expected: "M"
    replacement: "D"
  }
}
pages {
  page_number: 877
  patches {
    row: 3
    col: 2
    expected: "VV"
    replacement: "V/V"
  }
}
pages {
  page_number: 1017
  patches {
    row: 11
    col: 1
    expected: "imm8"
    replacement: "NA"
  }
  patches {
    row: 11
    col: 2
    expected: "NA"
    replacement: "imm8"
  }
}
pages {
  page_number: 1058
  patches {
    row: 11
    col: 2
    expected: "D"
    replacement: "M"
  }
  patches {
    row: 12
    col: 2
    expected: "D"
    replacement: "M"
  }
  patches {
    row: 13
    col: 2
    expected: "D"
    replacement: "M"
  }
}
pages {
  page_number: 1066
  patches {
    row: 3
    expected: "VEX.L1.0F.W0 4A /r \nKADDW k1, k2, k3"
    replacement: "VEX.NDS.L1.0F.W0 4A /r\nKADDW k1, k2, k3"
  }
  patches {
    row: 4
    expected: "VEX.L1.66.0F.W0 4A /r \nKADDB k1, k2, k3"
    replacement: "VEX.NDS.L1.66.0F.W0 4A /r\nKADDB k1, k2, k3"
  }
  patches {
    row: 5
    expected: "VEX.L1.0F.W1 4A /r \nKADDQ k1, k2, k3"
    replacement: "VEX.NDS.L1.0F.W1 4A /r\nKADDQ k1, k2, k3"
  }
  patches {
    row: 6
    expected: "VEX.L1.66.0F.W1 4A /r \nKADDD k1, k2, k3"
    replacement: "VEX.NDS.L1.66.0F.W1 4A /r\nKADDD k1, k2, k3"
  }
}
pages {
  page_number: 1067
  patches {
    row: 4
    expected: "VEX.L1.66.0F.W0 41 /r \nKANDB k1, k2, k3"
    replacement: "VEX.NDS.L1.66.0F.W0 41 /r\nKANDB k1, k2, k3"
  }
  patches {
    row: 5
    expected: "VEX.L1.0F.W1 41 /r \nKANDQ k1, k2, k3"
    replacement: "VEX.NDS.L1.0F.W1 41 /r\nKANDQ k1, k2, k3"
  }
  patches {
    row: 6
    expected: "VEX.L1.66.0F.W1 41 /r \nKANDD k1, k2, k3"
    replacement: "VEX.NDS.L1.66.0F.W1 41 /r\nKANDD k1, k2, k3"
  }
}
pages {
  page_number: 1068
  patches {
    row: 4
    expected: "VEX.L1.66.0F.W0 42 /r \nKANDNB k1, k2, k3"
    replacement: "VEX.NDS.L1.66.0F.W0 42 /r \nKANDNB k1, k2, k3"
  }
  patches {
    row: 5
    expected: "VEX.L1.0F.W1 42 /r \nKANDNQ k1, k2, k3"
    replacement: "VEX.NDS.L1.0F.W1 42 /r \nKANDNQ k1, k2, k3"
  }
  patches {
    row: 6
    expected: "VEX.L1.66.0F.W1 42 /r \nKANDND k1, k2, k3"
    replacement: "VEX.NDS.L1.66.0F.W1 42 /r \nKANDND k1, k2, k3"
  }
}
pages {
  page_number: 1072
  patches {
    row: 4
    expected: "VEX.L1.66.0F.W0 45 /r \nKORB k1, k2, k3"
    replacement: "VEX.NDS.L1.66.0F.W0 45 /r \nKORB k1, k2, k3"
  }
  patches {
    row: 5
    expected: "VEX.L1.0F.W1 45 /r \nKORQ k1, k2, k3"
    replacement: "VEX.NDS.L1.0F.W1 45 /r \nKORQ k1, k2, k3"
  }
  patches {
    row: 6
    expected: "VEX.L1.66.0F.W1 45 /r \nKORD k1, k2, k3"
    replacement: "VEX.NDS.L1.66.0F.W1 45 /r \nKORD k1, k2, k3"
  }
}
pages {
  page_number: 1082
  patches {
    row: 4
    expected: "VEX.L1.66.0F.W0 46 /r \nKXNORB k1, k2, k3"
    replacement: "VEX.NDS.L1.66.0F.W0 46 /r \nKXNORB k1, k2, k3"
  }
  patches {
    row: 5
    expected: "VEX.L1.0F.W1 46 /r \nKXNORQ k1, k2, k3"
    replacement: "VEX.NDS.L1.0F.W1 46 /r \nKXNORQ k1, k2, k3"
  }
  patches {
    row: 6
    expected: "VEX.L1.66.0F.W1 46 /r \nKXNORD k1, k2, k3"
    replacement: "VEX.NDS.L1.66.0F.W1 46 /r \nKXNORD k1, k2, k3"
  }
}
pages {
  page_number: 1083
  patches {
    row: 4
    expected: "VEX.L1.66.0F.W0 47 /r\nKXORB k1, k2, k3"
    replacement: "VEX.NDS.L1.66.0F.W0 47 /r\nKXORB k1, k2, k3"
  }
  patches {
    row: 5
    expected: "VEX.L1.0F.W1 47 /r \nKXORQ k1, k2, k3"
    replacement: "VEX.NDS.L1.0F.W1 47 /r \nKXORQ k1, k2, k3"
  }
  patches {
    row: 6
    expected: "VEX.L1.66.0F.W1 47 /r \nKXORD k1, k2, k3"
    replacement: "VEX.NDS.L1.66.0F.W1 47 /r \nKXORD k1, k2, k3"
  }
}
pages {
  page_number: 1175
  patches {
    row: 11
    expected: "VEX.128.66.0F.W0 6E /\nVMOVD xmm1, r32/m32"
    replacement: "VEX.128.66.0F.W0 6E /r\nVMOVD xmm1, r32/m32"
  }
}
pages {
  page_number: 1187
  patches {
    row: 21
    expected: "EVEX.128.F3.0F.W0 6F /r\nVMOVDQU32 xmm1 {k1}{z}, \nxmm2/mm128"
    replacement: "EVEX.128.F3.0F.W0 6F /r\nVMOVDQU32 xmm1 {k1}{z}, \nxmm2/m128"
  }
}
pages {
  page_number: 1204
  patches {
    row: 12
    col: 1
    expected: "ModRM:r/m (r)"
    replacement: "ModRM:reg (r)"
  }
}
pages {
  page_number: 1237
  patches {
    row: 3
    col: 1
    expected: "A"
    replacement: "RM"
  }
}
pages {
  page_number: 1246
  patches {
    row: 20
    expected: "RVM-MR"
    replacement: "FVM-MR"
  }
}
pages {
  page_number: 1250
  patches {
    row: 6
    expected: "VEX.128.0F 11.WIG /r\nVMOVUPS xmm2/m128, xmm1"
    replacement: "VEX.128.0F.WIG 11 /r\nVMOVUPS xmm2/m128, xmm1"
  }
  patches {
    row: 7
    expected: "VEX.256.0F 10.WIG /r\nVMOVUPS ymm1, ymm2/m256"
    replacement: "VEX.256.0F.WIG 10 /r\nVMOVUPS ymm1, ymm2/m256"
  }
  patches {
    row: 8
    expected: "VEX.256.0F 11.WIG /r\nVMOVUPS ymm2/m256, ymm1"
    replacement: "VEX.256.0F.WIG 11 /r\nVMOVUPS ymm2/m256, ymm1"
  }
  patches {
    row: 20
    expected: "RVM-MR"
    replacement: "FVM-MR"
  }
}
pages {
  page_number: 1276
  patches {
    row: 7
    col: 4
    expected: "RDX/EDX is implied 64/32 bits \nsource"
    replacement: "RDX/EDX"
  }
}
pages {
  page_number: 1301
  patches {
    row: 5
    expected: "VPABSD zmm1 {k1}{z}, zmm2/m512/m32bcst"
    replacement: "EVEX.512.66.0F38.W0 1E /r\nVPABSD zmm1 {k1}{z}, zmm2/m512/m32bcst"
  }
}
pages {
  page_number: 1314
  patches {
    row: 7
    expected: "EVEX.NDS.256.66.0F38.W0 2B /r"
    replacement: "EVEX.NDS.256.66.0F38.W0 2B /r\nVPACKUSDW ymm1{k1}{z},\nymm2, ymm3/m256/m32bcst"
  }
}
pages {
  page_number: 1335
  patches {
    row: 7
    expected: "VEX.NDS.128.660F.WIG DC /r\nVPADDUSB xmm1, xmm2, xmm3/m128"
    replacement: "VEX.NDS.128.66.0F.WIG DC /r\nVPADDUSB xmm1, xmm2, xmm3/m128"
  }
}
pages {
  page_number: 1394
  patches {
    row: 9
    col: 1
    expected: "T1S-MRI"
    replacement: "MRI"
  }
  patches {
    row: 10
    col: 1
    expected: "T1S-MRI"
    replacement: "MRI"
  }
  patches {
    row: 11
    col: 1
    expected: "T1S-MRI"
    replacement: "MRI"
  }
}
pages {
  page_number: 1397
  patches {
    row: 9
    col: 1
    expected: "T1S-\nMRI"
    replacement: "MRI"
  }
}
pages {
  page_number: 1470
  patches {
    row: 14
    expected: "VEX.128.66.0F 38.WIG 35 /r\nVPMOVZXDQ xmm1, xmm2/m64"
    replacement: "VEX.128.66.0F38.WIG 35 /r\nVPMOVZXDQ xmm1, xmm2/m64"
  }
}
pages {
  page_number: 1471
  patches {
    row: 2
    expected: "EVEX.128.66.0F38 30.WIG /r\nVPMOVZXBW xmm1 {k1}{z}, xmm2/m64"
    replacement: "EVEX.128.66.0F38.WIG 30 /r\nVPMOVZXBW xmm1 {k1}{z}, xmm2/m64"
  }
}
pages {
  page_number: 1524
  patches {
    row: 3
    col: 1
    expected: "A"
    replacement: "M"
  }
}
pages {
  page_number: 1578
  patches {
    row: 14
    col: 1
    expected: "FV"
    replacement: "FVI"
  }
  patches {
    row: 15
    col: 1
    expected: "FV"
    replacement: "FVI"
  }
}
pages {
  page_number: 1579
  patches {
    row: 1
    col: 1
    expected: "FV"
    replacement: "FVI"
  }
  patches {
    row: 2
    col: 1
    expected: "FV"
    replacement: "FVI"
  }
}
pages {
  page_number: 1609
  patches {
    row: 2
    col: 3
    expected: "CPUID \nFeature \nFlag"
    remove_cell: true
  }
}
pages {
  page_number: 1727
  patches {
    row: 6
    expected: "RMI"
    replacement: "RM0"
  }
}
pages {
  page_number: 1799
  patches {
    row: 3
    expected: "A8"
    replacement: "A8 ib"
  }
  patches {
    row: 3
    col: 1
    expected: "ib"
    remove_cell: true
  }
}
pages {
  page_number: 1801
  patches {
    row: 8
    expected: "A"
    replacement: "RM"
  }
}
pages {
  page_number: 1883
  patches {
    row: 4
    expected: "EVEX.256.0F.W1 78 02 /r\nVCVTTPD2UDQ xmm1 {k1}{z}, \nymm2/m256/m64bcst"
    replacement: "EVEX.256.0F.W1 78 /r\nVCVTTPD2UDQ xmm1 {k1}{z}, \nymm2/m256/m64bcst"
  }
}
pages {
  page_number: 2080
  patches {
    row: 9
    expected: "A"
    replacement: "RMV"
  }
}
pages {
  page_number: 2104
  patches {
    row: 9
    expected: "A"
    replacement: "RMV"
  }
}
pages {
  page_number: 2123
  patches {
    row: 8
    expected: "FVI"
    replacement: "FV"
  }
}
pages {
  page_number: 2127
  patches {
    row: 8
    expected: "FVI"
    replacement: "FV"
  }
}
pages {
  page_number: 2172
  patches {
    row: 8
    expected: "VPCMPUW k1 {k2}, zmm2, \nzmm3/m512, imm8"
    replacement: "EVEX.NDS.512.66.0F3A.W1 3E /r ib\nVPCMPUW k1 {k2}, zmm2, \nzmm3/m512, imm8"
  }
}
pages {
  page_number: 2200
  patches {
    row: 12
    expected: "EVEX.512.66.0F3A.W0 04 /r \nibVPERMILPS zmm1 {k1}{z}, \nzmm2/m512/m32bcst, imm8"
    replacement: "EVEX.512.66.0F3A.W0 04 /r ib\nVPERMILPS zmm1 {k1}{z}, \nzmm2/m512/m32bcst, imm8"
  }
}
pages {
  page_number: 2205
  patches {
    row: 4
    col: 1
    expected: "FV-RM"
    replacement: "FV-RMI"
  }
}
pages {
  page_number: 2208
  patches {
    row: 3
    expected: "VEX.256.66.0F38.W0 16 /r\nVPERMPS ymm1, ymm2, \nymm3/m256"
    replacement: "VEX.NDS.256.66.0F38.W0 16 /r\nVPERMPS ymm1, ymm2, \nymm3/m256"
  }
}
pages {
  page_number: 2211
  patches {
    row: 4
    col: 1
    expected: "FV-RM"
    replacement: "FV-RMI"
  }
}
pages {
  page_number: 2238
  patches {
    row: 3
    col: 1
    expected: "A"
    replacement: "HVM"
  }
  patches {
    row: 4
    col: 1
    expected: "A"
    replacement: "HVM"
  }
  patches {
    row: 5
    col: 1
    expected: "A"
    replacement: "HVM"
  }
  patches {
    row: 6
    col: 1
    expected: "A"
    replacement: "HVM"
  }
  patches {
    row: 7
    col: 1
    expected: "A"
    replacement: "HVM"
  }
  patches {
    row: 8
    col: 1
    expected: "A"
    replacement: "HVM"
  }
}
pages {
  page_number: 2328
  patches {
    row: 3
    expected: "EVEX.NDS.LIG.66.0F3A.W1 57\nVREDUCESD xmm1 {k1}{z}, \nxmm2, xmm3/m64{sae}, \nimm8/r"
    replacement: "EVEX.NDS.LIG.66.0F3A.W1 57 /r\nVREDUCESD xmm1 {k1}{z}, \nxmm2, xmm3/m64{sae}, \nimm8"
  }
}
pages {
  page_number: 2332
  patches {
    row: 3
    expected: "EVEX.NDS.LIG.66.0F3A.W0 57 \n/r /ib\nVREDUCESS xmm1 {k1}{z}, \nxmm2, xmm3/m32{sae}, \nimm8"
    replacement: "EVEX.NDS.LIG.66.0F3A.W0 57 \n/r ib\nVREDUCESS xmm1 {k1}{z}, \nxmm2, xmm3/m32{sae}, \nimm8"
  }
}
pages {
  page_number: 2410
  patches {
    row: 3
    col: 2
    expected: "O"
    replacement: "O1"
  }
  patches {
    row: 4
    col: 2
    expected: "O"
    replacement: "O2"
  }
  patches {
    row: 5
    col: 2
    expected: "O"
    replacement: "O1"
  }
  patches {
    row: 6
    col: 2
    expected: "O"
    replacement: "O1"
  }
  patches {
    row: 7
    col: 2
    expected: "O"
    replacement: "O2"
  }
  patches {
    row: 8
    col: 2
    expected: "O"
    replacement: "O2"
  }
  patches {
    row: 23
    expected: "O"
    replacement: "O1"
  }
  patches {
    row: 24
    expected: "O"
    replacement: "O2"
  }
}
