document_id {
  title: "Intel\302\256 64 and IA-32 Architectures Software Developers Manual, Combined Volumes: 1, 2A, 2B, 2C, 2D, 3A, 3B, 3C, 3D and 4"
  creation_date: "D:20170330225004Z"
  modification_date: "D:20170330230942-07\'00\'"
}
pages {
  page_number: 605
  patches {
    row: 6
    col: 1
    expected: "FV"
    replacement: "FV-RVM"
  }
  patches {
    row: 7
    col: 1
    expected: "FV"
    replacement: "FV-RVM"
  }
  patches {
    row: 8
    col: 1
    expected: "FV"
    replacement: "FV-RVM"
  }
}
pages {
  page_number: 608
  patches {
    row: 6
    col: 1
    expected: "FV"
    replacement: "FV-RVM"
  }
  patches {
    row: 7
    col: 1
    expected: "FV"
    replacement: "FV-RVM"
  }
  patches {
    row: 8
    col: 1
    expected: "FV"
    replacement: "FV-RVM"
  }
}
pages {
  page_number: 611
  patches {
    row: 5
    col: 1
    expected: "T1S"
    replacement: "T1S-RVM"
  }
}
pages {
  page_number: 694
  patches {
    row: 3
    col: 2
    expected: "M"
    replacement: "D"
  }
  patches {
    row: 4
    col: 2
    expected: "M"
    replacement: "D"
  }
}
pages {
  page_number: 825
  patches {
    row: 5
    expected: "VEX.LIG.F2.0F.W0 2D /r 1\nVCVTSD2SI r32, xmm1/m64"
    replacement: "VEX.LIG.F2.0F.W0 2D /r\nVCVTSD2SI r32, xmm1/m64"
  }
  patches {
    row: 6
    expected: "VEX.LIG.F2.0F.W1 2D /r 1\nVCVTSD2SI r64, xmm1/m64"
    replacement: "VEX.LIG.F2.0F.W1 2D /r\nVCVTSD2SI r64, xmm1/m64"
  }
}
pages {
  page_number: 835
  patches {
    row: 5
    expected: "VEX.LIG.F3.0F.W0 2D /r 1\nVCVTSS2SI r32, xmm1/m32"
    replacement: "VEX.LIG.F3.0F.W0 2D /r\nVCVTSS2SI r32, xmm1/m32"
  }
  patches {
    row: 6
    expected: "VEX.LIG.F3.0F.W1 2D /r 1\nVCVTSS2SI r64, xmm1/m32"
    replacement: "VEX.LIG.F3.0F.W1 2D /r\nVCVTSS2SI r64, xmm1/m32"
  }
}
pages {
  page_number: 846
  patches {
    row: 5
    expected: "VEX.LIG.F2.0F.W0 2C /r 1\nVCVTTSD2SI r32, xmm1/m64"
    replacement: "VEX.LIG.F2.0F.W0 2C /r\nVCVTTSD2SI r32, xmm1/m64"
  }
  patches {
    row: 6
    expected: "VEX.LIG.F2.0F.W1 2C /r 1\nVCVTTSD2SI r64, xmm1/m64"
    replacement: "VEX.LIG.F2.0F.W1 2C /r\nVCVTTSD2SI r64, xmm1/m64"
  }
}
pages {
  page_number: 848
  patches {
    row: 5
    expected: "VEX.LIG.F3.0F.W0 2C /r 1\nVCVTTSS2SI r32, xmm1/m32"
    replacement: "VEX.LIG.F3.0F.W0 2C /r\nVCVTTSS2SI r32, xmm1/m32"
  }
  patches {
    row: 6
    expected: "VEX.LIG.F3.0F.W1 2C /r 1\nVCVTTSS2SI r64, xmm1/m32"
    replacement: "VEX.LIG.F3.0F.W1 2C /r\nVCVTTSS2SI r64, xmm1/m32"
  }
}
pages {
  page_number: 879
  patches {
    row: 3
    col: 2
    expected: "VV"
    replacement: "V/V"
  }
}
pages {
  page_number: 961
  patches {
    row: 4
    col: 1
    expected: "FNSTCW*"
    replacement: "FNSTCW m2byte"
  }
  patches {
    row: 4
    col: 2
    expected: " m2byte"
    remove_cell: true
  }
}
pages {
  page_number: 963
  patches {
    row: 4
    col: 1
    expected: "FNSTENV*"
    replacement: "FNSTENV m14/28byte"
  }
  patches {
    row: 4
    col: 2
    expected: " m14/28byte"
    remove_cell: true
  }
}
pages {
  page_number: 965
  patches {
    row: 5
    col: 1
    expected: "FNSTSW*"
    replacement: "FNSTSW m2byte"
  }
  patches {
    row: 5
    col: 2
    expected: " m2byte"
    remove_cell: true
  }
}
pages {
  page_number: 997
  patches {
    row: 1
    col: 0
    expected: "FYL2XP1-Compute y ∗ log2"
    replacement: "FYL2XP1-Compute y ∗ log2(x+1)"
  }
  patches {
    row: 1
    col: 1
    expected: "(x +1)"
    remove_cell: true
  }
}
pages {
  page_number: 1019
  patches {
    row: 11
    col: 1
    expected: "imm8"
    replacement: "NA"
  }
  patches {
    row: 11
    col: 2
    expected: "NA"
    replacement: "imm8"
  }
}
pages {
  page_number: 1060
  patches {
    row: 11
    col: 2
    expected: "D"
    replacement: "M"
  }
  patches {
    row: 12
    col: 2
    expected: "D"
    replacement: "M"
  }
  patches {
    row: 13
    col: 2
    expected: "D"
    replacement: "M"
  }
}
pages {
  page_number: 1068
  patches {
    row: 3
    expected: "VEX.L1.0F.W0 4A /r \nKADDW k1, k2, k3"
    replacement: "VEX.NDS.L1.0F.W0 4A /r\nKADDW k1, k2, k3"
  }
  patches {
    row: 4
    expected: "VEX.L1.66.0F.W0 4A /r \nKADDB k1, k2, k3"
    replacement: "VEX.NDS.L1.66.0F.W0 4A /r\nKADDB k1, k2, k3"
  }
  patches {
    row: 5
    expected: "VEX.L1.0F.W1 4A /r \nKADDQ k1, k2, k3"
    replacement: "VEX.NDS.L1.0F.W1 4A /r\nKADDQ k1, k2, k3"
  }
  patches {
    row: 6
    expected: "VEX.L1.66.0F.W1 4A /r \nKADDD k1, k2, k3"
    replacement: "VEX.NDS.L1.66.0F.W1 4A /r\nKADDD k1, k2, k3"
  }
}
pages {
  page_number: 1069
  patches {
    row: 4
    expected: "VEX.L1.66.0F.W0 41 /r \nKANDB k1, k2, k3"
    replacement: "VEX.NDS.L1.66.0F.W0 41 /r\nKANDB k1, k2, k3"
  }
  patches {
    row: 5
    expected: "VEX.L1.0F.W1 41 /r \nKANDQ k1, k2, k3"
    replacement: "VEX.NDS.L1.0F.W1 41 /r\nKANDQ k1, k2, k3"
  }
  patches {
    row: 6
    expected: "VEX.L1.66.0F.W1 41 /r \nKANDD k1, k2, k3"
    replacement: "VEX.NDS.L1.66.0F.W1 41 /r\nKANDD k1, k2, k3"
  }
}
pages {
  page_number: 1070
  patches {
    row: 4
    expected: "VEX.L1.66.0F.W0 42 /r \nKANDNB k1, k2, k3"
    replacement: "VEX.NDS.L1.66.0F.W0 42 /r\nKANDNB k1, k2, k3"
  }
  patches {
    row: 5
    expected: "VEX.L1.0F.W1 42 /r \nKANDNQ k1, k2, k3"
    replacement: "VEX.NDS.L1.0F.W1 42 /r\nKANDNQ k1, k2, k3"
  }
  patches {
    row: 6
    expected: "VEX.L1.66.0F.W1 42 /r \nKANDND k1, k2, k3"
    replacement: "VEX.NDS.L1.66.0F.W1 42 /r\nKANDND k1, k2, k3"
  }
}
pages {
  page_number: 1074
  patches {
    row: 4
    expected: "VEX.L1.66.0F.W0 45 /r \nKORB k1, k2, k3"
    replacement: "VEX.NDS.L1.66.0F.W0 45 /r\nKORB k1, k2, k3"
  }
  patches {
    row: 5
    expected: "VEX.L1.0F.W1 45 /r \nKORQ k1, k2, k3"
    replacement: "VEX.NDS.L1.0F.W1 45 /r\nKORQ k1, k2, k3"
  }
  patches {
    row: 6
    expected: "VEX.L1.66.0F.W1 45 /r \nKORD k1, k2, k3"
    replacement: "VEX.NDS.L1.66.0F.W1 45 /r\nKORD k1, k2, k3"
  }
}
pages {
  page_number: 1084
  patches {
    row: 4
    expected: "VEX.L1.66.0F.W0 46 /r \nKXNORB k1, k2, k3"
    replacement: "VEX.NDS.L1.66.0F.W0 46 /r\nKXNORB k1, k2, k3"
  }
  patches {
    row: 5
    expected: "VEX.L1.0F.W1 46 /r \nKXNORQ k1, k2, k3"
    replacement: "VEX.NDS.L1.0F.W1 46 /r\nKXNORQ k1, k2, k3"
  }
  patches {
    row: 6
    expected: "VEX.L1.66.0F.W1 46 /r \nKXNORD k1, k2, k3"
    replacement: "VEX.NDS.L1.66.0F.W1 46 /r\nKXNORD k1, k2, k3"
  }
}
pages {
  page_number: 1085
  patches {
    row: 4
    expected: "VEX.L1.66.0F.W0 47 /r\nKXORB k1, k2, k3"
    replacement: "VEX.NDS.L1.66.0F.W0 47 /r\nKXORB k1, k2, k3"
  }
  patches {
    row: 5
    expected: "VEX.L1.0F.W1 47 /r \nKXORQ k1, k2, k3"
    replacement: "VEX.NDS.L1.0F.W1 47 /r\nKXORQ k1, k2, k3"
  }
  patches {
    row: 6
    expected: "VEX.L1.66.0F.W1 47 /r \nKXORD k1, k2, k3"
    replacement: "VEX.NDS.L1.66.0F.W1 47 /r\nKXORD k1, k2, k3"
  }
}
pages {
  page_number: 1177
  patches {
    row: 11
    expected: "VEX.128.66.0F.W0 6E /\nVMOVD xmm1, r32/m32"
    replacement: "VEX.128.66.0F.W0 6E /r\nVMOVD xmm1, r32/m32"
  }
}
pages {
  page_number: 1189
  patches {
    row: 21
    expected: "EVEX.128.F3.0F.W0 6F /r\nVMOVDQU32 xmm1 {k1}{z}, \nxmm2/mm128"
    replacement: "EVEX.128.F3.0F.W0 6F /r\nVMOVDQU32 xmm1 {k1}{z}, \nxmm2/m128"
  }
}
pages {
  page_number: 1206
  patches {
    row: 12
    col: 1
    expected: "ModRM:r/m (r)"
    replacement: "ModRM:reg (w)"
  }
}
pages {
  page_number: 1239
  patches {
    row: 3
    col: 1
    expected: "A"
    replacement: "RM"
  }
}
pages {
  page_number: 1248
  patches {
    row: 20
    expected: "RVM-MR"
    replacement: "FVM-MR"
  }
}
pages {
  page_number: 1252
  patches {
    row: 6
    expected: "VEX.128.0F 11.WIG /r\nVMOVUPS xmm2/m128, xmm1"
    replacement: "VEX.128.0F.WIG 11 /r\nVMOVUPS xmm2/m128, xmm1"
  }
  patches {
    row: 7
    expected: "VEX.256.0F 10.WIG /r\nVMOVUPS ymm1, ymm2/m256"
    replacement: "VEX.256.0F.WIG 10 /r\nVMOVUPS ymm1, ymm2/m256"
  }
  patches {
    row: 8
    expected: "VEX.256.0F 11.WIG /r\nVMOVUPS ymm2/m256, ymm1"
    replacement: "VEX.256.0F.WIG 11 /r\nVMOVUPS ymm2/m256, ymm1"
  }
  patches {
    row: 20
    expected: "RVM-MR"
    replacement: "FVM-MR"
  }
}
pages {
  page_number: 1278
  patches {
    row: 7
    col: 4
    expected: "RDX/EDX is implied 64/32 bits \nsource"
    replacement: "RDX/EDX"
  }
}
pages {
  page_number: 1303
  patches {
    row: 5
    expected: "VPABSD zmm1 {k1}{z}, zmm2/m512/m32bcst"
    replacement: "EVEX.512.66.0F38.W0 1E /r\nVPABSD zmm1 {k1}{z}, zmm2/m512/m32bcst"
  }
}
pages {
  page_number: 1316
  patches {
    row: 7
    expected: "EVEX.NDS.256.66.0F38.W0 2B /r"
    replacement: "EVEX.NDS.256.66.0F38.W0 2B /r\nVPACKUSDW ymm1{k1}{z}, ymm2, ymm3/m256/m32bcst"
  }
}
pages {
  page_number: 1337
  patches {
    row: 7
    expected: "VEX.NDS.128.660F.WIG DC /r\nVPADDUSB xmm1, xmm2, xmm3/m128"
    replacement: "VEX.NDS.128.66.0F.WIG DC /r\nVPADDUSB xmm1, xmm2, xmm3/m128"
  }
}
pages {
  page_number: 1396
  patches {
    row: 9
    col: 1
    expected: "T1S-MRI"
    replacement: "MRI"
  }
  patches {
    row: 10
    col: 1
    expected: "T1S-MRI"
    replacement: "MRI"
  }
  patches {
    row: 11
    col: 1
    expected: "T1S-MRI"
    replacement: "MRI"
  }
}
pages {
  page_number: 1399
  patches {
    row: 9
    col: 1
    expected: "T1S-\nMRI"
    replacement: "MRI"
  }
}
pages {
  page_number: 1472
  patches {
    row: 14
    expected: "VEX.128.66.0F 38.WIG 35 /r\nVPMOVZXDQ xmm1, xmm2/m64"
    replacement: "VEX.128.66.0F38.WIG 35 /r\nVPMOVZXDQ xmm1, xmm2/m64"
  }
}
pages {
  page_number: 1473
  patches {
    row: 2
    expected: "EVEX.128.66.0F38 30.WIG /r\nVPMOVZXBW xmm1 {k1}{z}, xmm2/m64"
    replacement: "EVEX.128.66.0F38.WIG 30 /r\nVPMOVZXBW xmm1 {k1}{z}, xmm2/m64"
  }
}
pages {
  page_number: 1526
  patches {
    row: 3
    col: 1
    expected: "A"
    replacement: "M"
  }
}
pages {
  page_number: 1580
  patches {
    row: 14
    col: 1
    expected: "FV"
    replacement: "FVI"
  }
  patches {
    row: 15
    col: 1
    expected: "FV"
    replacement: "FVI"
  }
}
pages {
  page_number: 1581
  patches {
    row: 1
    col: 1
    expected: "FV"
    replacement: "FVI"
  }
  patches {
    row: 2
    col: 1
    expected: "FV"
    replacement: "FVI"
  }
}
pages {
  page_number: 1611
  patches {
    row: 2
    col: 3
    expected: "CPUID \nFeature \nFlag"
    remove_cell: true
  }
}
pages {
  page_number: 1729
  patches {
    row: 3
    col: 1
    expected: "RM0"
    replacement: "RMI"
  }
}
pages {
  page_number: 1801
  patches {
    row: 3
    expected: "A8"
    replacement: "A8 ib"
  }
  patches {
    row: 3
    col: 1
    expected: "ib"
    remove_cell: true
  }
}
pages {
  page_number: 1803
  patches {
    row: 8
    expected: "A"
    replacement: "RM"
  }
}
pages {
  page_number: 1885
  patches {
    row: 4
    expected: "EVEX.256.0F.W1 78 02 /r\nVCVTTPD2UDQ xmm1 {k1}{z}, \nymm2/m256/m64bcst"
    replacement: "EVEX.256.0F.W1 78 /r\nVCVTTPD2UDQ xmm1 {k1}{z}, \nymm2/m256/m64bcst"
  }
}
pages {
  page_number: 2082
  patches {
    row: 9
    expected: "A"
    replacement: "RMV"
  }
}
pages {
  page_number: 2106
  patches {
    row: 9
    expected: "A"
    replacement: "RMV"
  }
}
pages {
  page_number: 2125
  patches {
    row: 8
    expected: "FVI"
    replacement: "FV"
  }
}
pages {
  page_number: 2129
  patches {
    row: 8
    expected: "FVI"
    replacement: "FV"
  }
}
pages {
  page_number: 2174
  patches {
    row: 8
    expected: "VPCMPUW k1 {k2}, zmm2, \nzmm3/m512, imm8"
    replacement: "EVEX.NDS.512.66.0F3A.W1 3E /r ib\nVPCMPUW k1 {k2}, zmm2, zmm3/m512, imm8"
  }
}
pages {
  page_number: 2202
  patches {
    row: 12
    expected: "EVEX.512.66.0F3A.W0 04 /r \nibVPERMILPS zmm1 {k1}{z}, \nzmm2/m512/m32bcst, imm8"
    replacement: "EVEX.512.66.0F3A.W0 04 /r ib\nVPERMILPS zmm1 {k1}{z}, \nzmm2/m512/m32bcst, imm8"
  }
}
pages {
  page_number: 2207
  patches {
    row: 4
    col: 1
    expected: "FV-RM"
    replacement: "FV-RMI"
  }
}
pages {
  page_number: 2210
  patches {
    row: 3
    expected: "VEX.256.66.0F38.W0 16 /r\nVPERMPS ymm1, ymm2, \nymm3/m256"
    replacement: "VEX.NDS.256.66.0F38.W0 16 /r\nVPERMPS ymm1, ymm2, \nymm3/m256"
  }
}
pages {
  page_number: 2213
  patches {
    row: 4
    col: 1
    expected: "FV-RM"
    replacement: "FV-RMI"
  }
}
pages {
  page_number: 2240
  patches {
    row: 3
    col: 1
    expected: "A"
    replacement: "HVM"
  }
  patches {
    row: 4
    col: 1
    expected: "A"
    replacement: "HVM"
  }
  patches {
    row: 5
    col: 1
    expected: "A"
    replacement: "HVM"
  }
  patches {
    row: 6
    col: 1
    expected: "A"
    replacement: "HVM"
  }
  patches {
    row: 7
    col: 1
    expected: "A"
    replacement: "HVM"
  }
  patches {
    row: 8
    col: 1
    expected: "A"
    replacement: "HVM"
  }
}
pages {
  page_number: 2330
  patches {
    row: 3
    expected: "EVEX.NDS.LIG.66.0F3A.W1 57\nVREDUCESD xmm1 {k1}{z}, \nxmm2, xmm3/m64{sae}, \nimm8/r"
    replacement: "EVEX.NDS.LIG.66.0F3A.W1 57 /r\nVREDUCESD xmm1 {k1}{z}, \nxmm2, xmm3/m64{sae}, \nimm8"
  }
}
pages {
  page_number: 2334
  patches {
    row: 3
    expected: "EVEX.NDS.LIG.66.0F3A.W0 57 \n/r /ib\nVREDUCESS xmm1 {k1}{z}, \nxmm2, xmm3/m32{sae}, \nimm8"
    replacement: "EVEX.NDS.LIG.66.0F3A.W0 57 /r ib\nVREDUCESS xmm1 {k1}{z}, \nxmm2, xmm3/m32{sae}, \nimm8"
  }
}
pages {
  page_number: 2412
  patches {
    row: 3
    col: 2
    expected: "O"
    replacement: "O1"
  }
  patches {
    row: 4
    col: 2
    expected: "O"
    replacement: "O2"
  }
  patches {
    row: 5
    col: 2
    expected: "O"
    replacement: "O1"
  }
  patches {
    row: 6
    col: 2
    expected: "O"
    replacement: "O1"
  }
  patches {
    row: 7
    col: 2
    expected: "O"
    replacement: "O2"
  }
  patches {
    row: 8
    col: 2
    expected: "O"
    replacement: "O2"
  }
  patches {
    row: 23
    expected: "O"
    replacement: "O1"
  }
  patches {
    row: 24
    expected: "O"
    replacement: "O2"
  }
  patches {
    row: 25
    col: 2
    expected: "ModRM:reg (r)"
    replacement: "ModRM:reg (r, w)"
  }
  patches {
    row: 26
    col: 1
    expected: "ModRM:reg (w)"
    replacement: "ModRM:reg (r, w)"
  }
  patches {
    row: 26
    col: 2
    expected: "ModRM:r/m (r)"
    replacement: "ModRM:r/m (r, w)"
  }
}
